use_frameworks!

platform :ios, '8.0'

target 'GADesignNetwork_Example' do
  pod 'GADesignNetwork', :path => '../'

  target 'GADesignNetwork_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
